### ISSUE TITLE
About PSNR

### ISSUE THREAD

**Issue by eedalong** [cchen156/Learning-to-See-in-the-Dark#27]
Hi  @cchen156 i test psnr of ur model on test samples 1-49 in ur test_list.txt , and the psnr is ~32dB ,is that the same with urs ? i didnt change any of ur codes 
My PSNR Calculation ：
PSNR（img1,img2）:
      mse = np.mean((img1 - img2)^2)
     return 10*np.log10(255^2 / mse);

**Comment by cchen156** [comment]
I test the images using MATLAB.

**Comment by yxlao** [comment]
@eedalong you'll need to cast `img1` and `img2` to floating point before doing `np.mean`. The reason is that `img1` and `img2` are of type `uint8`, so `img1 - img2` being `uint8` is always non negative. 

```python
def get_psnr(im1, im2):
    im1 = np.asarray(im1, dtype=np.float64)
    im2 = np.asarray(im2, dtype=np.float64)
    mse = np.mean(np.square(im1 - im2))
    return 10. * np.log10(np.square(255.) / mse)
```

Using the pretrained model provided by @cchen156, I'm getting 28.61dB for the full test set, which almost matches the published result.
