### ISSUE TITLE
using jpeg instead of raw

### ISSUE THREAD

**Issue by Jayanth-L** [cchen156/Learning-to-See-in-the-Dark#81]
Can you please explain why can't we use jpg instead of raw ?

**Comment by Groenbech96** [comment]
You have to consider the fact that a jpg is a 3 channel image, and the ARW file format is converted into a 4 channel input. If you want to use jpg, then you first need to change the structure of input layer.

**Comment by Jayanth-L** [comment]
Does it has anything to do with RAW vanilla data and jpeg compression ?

**Comment by Groenbech96** [comment]
ARW files have a Bayer sensor and has a format called RGGB / RGBG. 
If you take a look at their implementation they stack 4 channels before inputting it to the model, and this is because the sensor creates twice as many green pixels as red and blue (RGBG <- two Gs). 
JPEG is a RGB format, hence it has an equal amount of red, green and blue pixels, and is therefore considered to be 3 channels. You can indeed use RGB formatted images, but you have to change the architecture of the network. 

I hope this answers your question

**Comment by Jayanth-L** [comment]
Thank you very much for explaining :)

**Comment by willswordh** [comment]
> You have to consider the fact that a jpg is a 3 channel image, and the ARW file format is converted into a 4 channel input. If you want to use jpg, then you first need to change the structure of input layer.

@Groenbech96 Hi, do you know for using jpg picture, what is the specific approaches to change the structure of input layer?
